name: Build and Deploy
on:
  push:
    branches: [ main ]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: get source code
      uses: actions/checkout@v3
    - name: setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: install Pnpm  
      uses: pnpm/action-setup@v2
      id: pnpm-install
      with:
          version: 7
          run_install: true
    - name: install packages
      run: pnpm install
    - name: build
      run: |
        npm run build
        touch out/.nojekyll
    - name: replace
      run: |
        find out -type f -exec sed -i 's|/vivoCamera.github.io/|https://vivoCamera.github.io/|g' {} +      
    - name: deploy 
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: gh-pages
        folder: out
        clean: true